-- phpMyAdmin SQL Dump
-- version 5.0.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Sep 19, 2023 at 02:25 PM
-- Server version: 10.4.11-MariaDB
-- PHP Version: 7.4.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `youtube_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `youtube_channels`
--

CREATE TABLE `youtube_channels` (
  `y_id` int(11) NOT NULL,
  `yc_url` varchar(100) NOT NULL,
  `profile_pic` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` longtext NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `youtube_channels`
--

INSERT INTO `youtube_channels` (`y_id`, `yc_url`, `profile_pic`, `name`, `description`, `created_at`) VALUES
(122, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://yt3.ggpht.com/ytc/AOPolaSgxdcGCTetw5XYCoLiNlK61Mh2WQV2aD956u-g=s800-c-k-c0x00ffffff-no-rj', 'Key & Peele', 'The Key & Peele channel is the place to watch comedy sketches from Keegan-Michael Key and Jordan Peele, whose Comedy Central show took on everything from \"Gremlins 2\" to systemic racism. With an array of sketches as far-reaching as they are cringingly accurate, the pair has created a bevy of classic characters, including Wendell, Mr. Garvey the substitute teacher, the players of the East/West Bowl and President Obama\'s Anger Translator. Check out more at https://www.paramountplus.com/shows/key-and-peele/ ', '2019-01-02 12:29:38'),
(123, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://yt3.ggpht.com/mN3w_CAMgYp9gQeNfOvMGkZHJWSD9H48ZeLRd8EhXsiOjY6c1Wse_fFdXIGwApH4CXxmnwIFvQ=s800-c-k-c0x00ffffff-no-rj', 'GMA Pinoy TV', 'As GMA Network’s flagship international channel, GMA Pinoy TV delivers exceptional Filipino entertainment and news programming since its inception in 2005. GMA Life TV, on the other hand, was launched in 2008 and delivers a diverse range of program genres that include lifestyle, travel, food, health and beauty, talk and infotainment, blockbuster movies, and top-rated English-dubbed drama series, all available in English and Filipino. Backed by the most trusted and multi-awarded Philippine news and public affairs teams, GMA News TV has been providing global Filipinos with the latest, most comprehensive, and most credible news from the Philippines since 2011. GMA On Demand is the go-to source for the most premium content from GMA with its unparalleled selection of catch-up, subscription, and transactional VOD content.\n\nGMA Pinoy TV, the home of Global Pinoys, marks its 18th Anniversary in the US this August 2023.\n', '2019-03-18 22:21:42');

-- --------------------------------------------------------

--
-- Table structure for table `youtube_channel_videos`
--

CREATE TABLE `youtube_channel_videos` (
  `v_id` int(11) NOT NULL,
  `yc_id` varchar(100) NOT NULL,
  `video_link` varchar(255) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` longtext NOT NULL,
  `thumbnail` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `youtube_channel_videos`
--

INSERT INTO `youtube_channel_videos` (`v_id`, `yc_id`, `video_link`, `title`, `description`, `thumbnail`) VALUES
(1747, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/SiRIcrElgMM', 'Key &amp; Peele’s Most Convincing Accents 🇬🇧🏴‍☠️', 'A look back at Key & Peele sketches proving their ability to pull off any accent. Paramount+ is here! Stream Key & Peele now on ...', 'https://i.ytimg.com/vi/SiRIcrElgMM/hqdefault.jpg'),
(1748, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/ddFyiVYbOuw', 'Mmm, seems like concussion protocol is in order here. | #shorts #keyandpeele', '', 'https://i.ytimg.com/vi/ddFyiVYbOuw/hqdefault.jpg'),
(1749, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/xo01ziocMcE', 'When the improv group already has a black guy | #keyandpeele #shorts', '', 'https://i.ytimg.com/vi/xo01ziocMcE/hqdefault.jpg'),
(1750, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/0O_D1vzVtt0', 'When your mnemonic device is wayyy too complicated | #keyandpeele #shorts', '', 'https://i.ytimg.com/vi/0O_D1vzVtt0/hqdefault.jpg'),
(1751, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/ZqdTiok7xfg', 'Starting to think maybe he’s not a real sensei… | #keyandpeele #shorts', '', 'https://i.ytimg.com/vi/ZqdTiok7xfg/hqdefault.jpg'),
(1752, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/FubBwCMRveA', 'TFW your friend goes steampunk | #shorts #keyandpeele', '', 'https://i.ytimg.com/vi/FubBwCMRveA/hqdefault.jpg'),
(1753, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/l5wdNy2qoaA', 'Key &amp; Peele’s Most Intense Interrogations 🔎', 'These Key & Peele interrogations aren\'t afraid to get intense. Like, really intense. Paramount+ is here! Stream Key & Peele now ...', 'https://i.ytimg.com/vi/l5wdNy2qoaA/hqdefault.jpg'),
(1754, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/QPi280q3gWY', 'When the a cappella group already has one black guy | #shorts #keyandpeele', '', 'https://i.ytimg.com/vi/QPi280q3gWY/hqdefault.jpg'),
(1755, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/1JfY9I1Y9B8', 'And this is why British actors end up with all the good roles. | #shorts #keyandpeele', '', 'https://i.ytimg.com/vi/1JfY9I1Y9B8/hqdefault.jpg'),
(1756, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/bYbqYUwbND0', '“Uh, I actually pressed it already.” 🙄 | #shorts #keyandpeele', '', 'https://i.ytimg.com/vi/bYbqYUwbND0/hqdefault.jpg'),
(1757, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/HO9WwohU2oU', 'You don’t want to be bad at counting in this scenario | #shorts #keyandpeele', '', 'https://i.ytimg.com/vi/HO9WwohU2oU/hqdefault.jpg'),
(1758, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/gyavV_v19Uc', 'Key &amp; Peele’s Most Unpredictable Bosses 🤯', 'There\'s absolutely no predicting what these bosses on Key & Peele will do next. Paramount+ is here! Stream Key & Peele now on ...', 'https://i.ytimg.com/vi/gyavV_v19Uc/hqdefault.jpg'),
(1759, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/IMtXCY1Wsw4', '“What is that?” | #shorts #keyandpeele', '', 'https://i.ytimg.com/vi/IMtXCY1Wsw4/hqdefault.jpg'),
(1760, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/j8G2BBwPq-I', 'The last person you want to run into post-apocalypse. | #shorts #keyandpeele', '', 'https://i.ytimg.com/vi/j8G2BBwPq-I/hqdefault.jpg'),
(1761, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/noLe_F5rRkg', 'Why doesn’t anyone get to meet Mr. Mahina? | #shorts #keyandpeele', '', 'https://i.ytimg.com/vi/noLe_F5rRkg/hqdefault.jpg'),
(1762, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/oLytSvYPslg', 'Key &amp; Peele’s Best Movie Sketches 🎥', 'From talking about movies to pitching them, here are some of Key & Peele\'s funniest sketches. Paramount+ is here! Stream Key ...', 'https://i.ytimg.com/vi/oLytSvYPslg/hqdefault.jpg'),
(1763, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/62hYwmShjGA', '“I ain’t tryin’ to fight nobody with a baby.” | #shorts #keyandpeele', '', 'https://i.ytimg.com/vi/62hYwmShjGA/hqdefault.jpg'),
(1764, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/zkMBezEINCk', 'Brotherly love is irreplaceable. | #shorts #keyandpeele', '', 'https://i.ytimg.com/vi/zkMBezEINCk/hqdefault.jpg'),
(1765, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/oQkjmb3aAls', 'Key &amp; Peele’s Biggest Miscommunications 🤨', 'The characters in these Key & Peele sketches have one thing in common: the inability to understand what\'s going on around them ...', 'https://i.ytimg.com/vi/oQkjmb3aAls/hqdefault.jpg'),
(1766, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/o6dNYnyywaE', 'So… do you promise? | #keyandpeele #shorts', '', 'https://i.ytimg.com/vi/o6dNYnyywaE/hqdefault.jpg'),
(1767, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/OKC2Nf5DkP4', 'Key &amp; Peele’s Fiercest Rivalries 😡', 'From actors to MMA fighters, here are some of Key & Peele\'s fiercest rivalries. Paramount+ is here! Stream Key & Peele now on ...', 'https://i.ytimg.com/vi/OKC2Nf5DkP4/hqdefault.jpg'),
(1768, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/O0_oBHBojOk', 'The most awkward run-in you can have | #keyandpeele  #shorts', '', 'https://i.ytimg.com/vi/O0_oBHBojOk/hqdefault.jpg'),
(1769, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/q6wJPxnd49Y', 'Key &amp; Peele’s Bravest Rule Breakers 🤪', 'These Key & Peele characters proudly broke the rules and had to live with the consequences. Paramount+ is here! Stream Key ...', 'https://i.ytimg.com/vi/q6wJPxnd49Y/hqdefault.jpg'),
(1770, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/6Q1oD8m0QH8', 'Judge Jessie proves he has the know-how to settle any dispute. | #shorts #keyandpeele', '', 'https://i.ytimg.com/vi/6Q1oD8m0QH8/hqdefault.jpg'),
(1771, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/nqoc2CCePPA', 'Key &amp; Peele’s Most Socially Awkward Moments', 'These Key & Peele sketches will have you laughing and cringing at the same time. Paramount+ is here! Stream Key & Peele now ...', 'https://i.ytimg.com/vi/nqoc2CCePPA/hqdefault.jpg'),
(1772, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/0XxM8b1cFvw', '“I am a SOCIOPATH!” | #keyandpeele #shorts', '', 'https://i.ytimg.com/vi/0XxM8b1cFvw/hqdefault.jpg'),
(1773, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/Jr0flqVNPK0', 'Fan-Favorite Moments: Season 3 😂', 'A look back at fan-favorite, unforgettable moments from Season 3 of Key & Peele. Paramount+ is here! Stream Key & Peele now ...', 'https://i.ytimg.com/vi/Jr0flqVNPK0/hqdefault.jpg'),
(1774, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/A_PajWngBg4', 'Best Of Key &amp; Peele’s Time Travel ⏳', 'From 1852 to The Future, here\'s proof of Key & Peele\'s existence in any era. Paramount+ is here! Stream Key & Peele now on ...', 'https://i.ytimg.com/vi/A_PajWngBg4/hqdefault.jpg'),
(1775, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/3S5vHEozoVI', 'Strangest Customer Service Encounters 😤 Key &amp; Peele', 'From a flight attendant with very specific requests to a telemarketer with an unusual approach, here are some of Key & Peele\'s ...', 'https://i.ytimg.com/vi/3S5vHEozoVI/hqdefault.jpg'),
(1776, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/ACEwbE1Ppzw', 'It’s the little things that count. | #shorts #keyandpeele', '', 'https://i.ytimg.com/vi/ACEwbE1Ppzw/hqdefault.jpg'),
(1777, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/AAitaPYtlKE', 'Keegan-Michael Key got so deep into character for the #supermariomovie it freaked out his costars', 'Watch the full video on @ComedyCentral: https://www.youtube.com/watch?v=6hNE97V50vw.', 'https://i.ytimg.com/vi/AAitaPYtlKE/hqdefault.jpg'),
(1778, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/fwtwvkzeTKU', 'Fan-Favorite Moments: Season 2 🏆 Key &amp; Peele', 'A look back at fan-favorite, unforgettable moments from Season 2 of Key & Peele. Paramount+ is here! Stream Key & Peele now ...', 'https://i.ytimg.com/vi/fwtwvkzeTKU/hqdefault.jpg'),
(1779, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/Q473apc6QT8', '&quot;MEMES!&quot; | #shorts #keyandpeele', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf.', 'https://i.ytimg.com/vi/Q473apc6QT8/hqdefault.jpg'),
(1780, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/r0RO3Q63K5o', 'Top 15 Most Watched Key &amp; Peele Shorts 🏆', 'Here are the top 15 Key & Peele YouTube Shorts. Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at ...', 'https://i.ytimg.com/vi/r0RO3Q63K5o/hqdefault.jpg'),
(1781, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/d2kVYJ-5fIE', '&quot;C&#39;mon, chill it out, Black Falcon.&quot; | #Shorts #keyandpeele', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf.', 'https://i.ytimg.com/vi/d2kVYJ-5fIE/hqdefault.jpg'),
(1782, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/MEjWAnT2j3s', 'Key &amp; Peele’s Most Intense Competitions 💪', 'From a TV talent show to high school clubs, these Key & Peele characters will go to extreme lengths to beat the competition.', 'https://i.ytimg.com/vi/MEjWAnT2j3s/hqdefault.jpg'),
(1783, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/d-1HzCu-iLA', 'Come inside. | #shorts #keyandpeele', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf.', 'https://i.ytimg.com/vi/d-1HzCu-iLA/hqdefault.jpg'),
(1784, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/JspfS_xTRMM', 'Key &amp; Peele’s Supernatural Experiences 👽', 'A look back at some of Key & Peele\'s most unforgettable experiences with aliens, demons, and more. Paramount+ is here! Stream ...', 'https://i.ytimg.com/vi/JspfS_xTRMM/hqdefault.jpg'),
(1785, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/Xy1AjTsFg5U', 'when you have a song for your best friend | #shorts #keyandpeele', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf.', 'https://i.ytimg.com/vi/Xy1AjTsFg5U/hqdefault.jpg'),
(1786, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/4Z3I_0eUDsQ', 'Fan-Favorite Moments: Season 1 😎', 'A look back at fan-favorite, unforgettable moments from Season 1 of Key & Peele. Paramount+ is here! Stream Key & Peele now ...', 'https://i.ytimg.com/vi/4Z3I_0eUDsQ/hqdefault.jpg'),
(1787, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/BMxQ3DAfLrw', 'when the solo&#39;s too fire 🔥 | #shorts #keyandpeele', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf.', 'https://i.ytimg.com/vi/BMxQ3DAfLrw/hqdefault.jpg'),
(1788, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/5uqfx63e0KU', 'Key &amp; Peele’s Most Intense Locker Rooms ⚾️', 'From a post-game interview gone wrong to over-the-top camaraderie, here\'s a look at Key & Peele\'s funniest locker room sketches ...', 'https://i.ytimg.com/vi/5uqfx63e0KU/hqdefault.jpg'),
(1789, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/Wkm5nRpjJJ8', '“But is it against the law, though?” | #shorts #keyandpeele', '', 'https://i.ytimg.com/vi/Wkm5nRpjJJ8/hqdefault.jpg'),
(1790, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/oIisw8CCdd8', 'Key &amp; Peele’s Most Chaotic Games 🃏', 'From secrets revealed during a game of Celebrity to a fondness for a game that no one should like, here\'s a look at some of Key ...', 'https://i.ytimg.com/vi/oIisw8CCdd8/hqdefault.jpg'),
(1791, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/sMw001gS2Ps', 'Key &amp; Peele’s Worst Liars 🤥', 'From a rapper whose mixtape gives away his secret to two swindlers looking to outsmart each other, here\'s a look at some of Key ...', 'https://i.ytimg.com/vi/sMw001gS2Ps/hqdefault.jpg'),
(1792, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/Kl-VRiIQzns', 'the dolphins: why is it spicy 💩| #shorts #keyandpeele', '', 'https://i.ytimg.com/vi/Kl-VRiIQzns/hqdefault.jpg'),
(1793, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/Q1BaXoPvoZE', 'Key &amp; Peele’s Most Complicated Couples 💕', 'From a couple (very publicly) not on the same page to a very quiet double date, here\'s a look back at some of Key & Peele\'s most ...', 'https://i.ytimg.com/vi/Q1BaXoPvoZE/hqdefault.jpg'),
(1794, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/Yl_r-LdzeEw', 'Yo ho ho, but no disrespect. | #shorts #keyandpeele', '', 'https://i.ytimg.com/vi/Yl_r-LdzeEw/hqdefault.jpg'),
(1795, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/ZLG_RWROi5I', 'Key &amp; Peele’s Unforgettable Food Sketches 🍴', 'From a confusing chef to BBQ gone wrong, here\'s a look at some of Key & Peele\'s most unforgettable food sketches. Paramount+ ...', 'https://i.ytimg.com/vi/ZLG_RWROi5I/hqdefault.jpg'),
(1796, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/agQKBrtr3gE', 'One wrong move can destroy a substitute teacher | #shorts #keyandpeele', '', 'https://i.ytimg.com/vi/agQKBrtr3gE/hqdefault.jpg'),
(1797, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/YdS8XFEFxWg', 'Key &amp; Peele’s Questionable Doctor Visits 🤔', 'From a doctor who is willing to play along (within reason) to one who has an easy diagnosis, here\'s a look back at some of Key ...', 'https://i.ytimg.com/vi/YdS8XFEFxWg/hqdefault.jpg'),
(1798, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/RLUJxoIkRJg', '&quot;I&#39;d buy that dude.&quot; | #shorts #keyandpeele | Subscribe to Key &amp; Peele👇', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf.', 'https://i.ytimg.com/vi/RLUJxoIkRJg/hqdefault.jpg'),
(1799, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/D1ZPrcz0P4M', 'Key &amp; Peele’s Most Over-The-Top Fashion 🎩', 'From next-level hats to a terrifying encounter for a tailor, here are some of Key & Peele\'s most unforgettable fashion-centric ...', 'https://i.ytimg.com/vi/D1ZPrcz0P4M/hqdefault.jpg'),
(1800, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/_dN2FC3KSJk', 'Wanna play Fronthand Backhand? | #shorts #keyandpeele | Subscribe to Key &amp; Peele 👇', '', 'https://i.ytimg.com/vi/_dN2FC3KSJk/hqdefault.jpg'),
(1801, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/f8ZkieyFydM', 'Key &amp; Peele’s Most Unforgettable Plane Rides 🛩', 'From an unexpected seat upgrade to a not-so-special boarding group, here are some of Key & Peele\'s most unforgettable plane ...', 'https://i.ytimg.com/vi/f8ZkieyFydM/hqdefault.jpg'),
(1802, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/QW6LPj8T-LE', 'Rules are rules | #excessivecelebration #football #shorts', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf.', 'https://i.ytimg.com/vi/QW6LPj8T-LE/hqdefault.jpg'),
(1803, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/wRbIxYrL2no', 'How to pour one out... when you also really want that drink | #shorts', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf.', 'https://i.ytimg.com/vi/wRbIxYrL2no/hqdefault.jpg'),
(1804, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/Ln6wZHDFDtg', 'Most Watched of 2022 🥳 Key &amp; Peele', 'From a sad sibling rivalry to some suspicious activity at a pawn shop, here are the most watched Key & Peele sketches of 2022.', 'https://i.ytimg.com/vi/Ln6wZHDFDtg/hqdefault.jpg'),
(1805, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/2S_nhuXHtJ8', 'Boarding a plane be like…', '', 'https://i.ytimg.com/vi/2S_nhuXHtJ8/hqdefault.jpg'),
(1806, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/dWMeIeLmptY', 'Best of East/West Bowl Sketches 🏈 Key &amp; Peele', 'Here\'s a look back at the best of Key & Peele\'s East/West sketches. If this inspires you to watch some football, don\'t miss the NFL ...', 'https://i.ytimg.com/vi/dWMeIeLmptY/hqdefault.jpg'),
(1807, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/kVNixOxZgtE', 'Key &amp; Peele’s Next-Level Trash Talk 🤬', 'From unexpected burns from a doctor to an intense pre-fight exchange, here\'s a look at some of Key & Peele\'s most intense trash ...', 'https://i.ytimg.com/vi/kVNixOxZgtE/hqdefault.jpg'),
(1808, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/qw1i1GxSIaw', 'It&#39;s your classic holiday song... with a twist.', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf.', 'https://i.ytimg.com/vi/qw1i1GxSIaw/hqdefault.jpg'),
(1809, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/K2R1mav3sz0', 'Key &amp; Peele’s Coldest Sketches 🥶', 'From a spin on a holiday classic to an undercover cop who goes hard on fro-yo, here\'s a look at some of Key & Peele\'s coldest ...', 'https://i.ytimg.com/vi/K2R1mav3sz0/hqdefault.jpg'),
(1810, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/mM2Sfl600Cg', 'Order up. | #Shorts #KeyAndPeele', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf.', 'https://i.ytimg.com/vi/mM2Sfl600Cg/hqdefault.jpg'),
(1811, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/qLvxc83GrM4', 'Key &amp; Peele’s Not-So-Clever Criminals 😳', 'Form an in-depth bank robbery to a very literal gangster, here\'s a look back at some of Key & Peele\'s funniest criminals.', 'https://i.ytimg.com/vi/qLvxc83GrM4/hqdefault.jpg'),
(1812, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/_9KnKjWuiOA', 'The saddest sibling rivalry | #shorts #keyandpeele', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf.', 'https://i.ytimg.com/vi/_9KnKjWuiOA/hqdefault.jpg'),
(1813, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/qj5scSYOD4I', 'Best of Key &amp; Peele: Intense Family Edition 😰', 'From unaccepting parents to a hard-to-please brother, these Key & Peele sketches are all about family. Paramount+ is here!', 'https://i.ytimg.com/vi/qj5scSYOD4I/hqdefault.jpg'),
(1814, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/eoPbN0wWqsY', 'An expert futbol flop | #shorts #keyandpeele #worldcup', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf.', 'https://i.ytimg.com/vi/eoPbN0wWqsY/hqdefault.jpg'),
(1815, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/qL4LiFpeOZY', 'Key &amp; Peele’s Craziest Plot Twists 😱', 'From secrets to country music, no one saw these plot twists coming. Paramount+ is here! Stream Key & Peele now on Paramount+ ...', 'https://i.ytimg.com/vi/qL4LiFpeOZY/hqdefault.jpg'),
(1816, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/4MYHRYbcq0c', 'Best Of Key &amp; Peele: Next-Level Technology 📱', 'From a new app to a video game gone wrong, here\'s a look back at some of Key & Peele\'s funniest technology sketches.', 'https://i.ytimg.com/vi/4MYHRYbcq0c/hqdefault.jpg'),
(1817, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/_nD1Y_JapQs', 'When your hair is your entire personality | #shorts #keyandpeele', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf.', 'https://i.ytimg.com/vi/_nD1Y_JapQs/hqdefault.jpg'),
(1818, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/0gNA7EHzmGw', 'Best Of Key &amp; Peele: Politics Edition 🤝', 'From President Obama to Black Republicans, here\'s a look back at some of Key & Peele\'s most unforgettable political sketches.', 'https://i.ytimg.com/vi/0gNA7EHzmGw/hqdefault.jpg'),
(1819, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/ZvkWUHhs8W8', 'Hee hee. #KeyAndPeele #michaeljackson #halloweencostume', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf.', 'https://i.ytimg.com/vi/ZvkWUHhs8W8/hqdefault.jpg'),
(1820, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/NfkPaK05iEk', 'Key &amp; Peele&#39;s Best Halloween Sketches 🧟', 'From racist zombies to vampires trying to be too sexy, here\'s a look back at some Key & Peele sketches to get you in the ...', 'https://i.ytimg.com/vi/NfkPaK05iEk/hqdefault.jpg'),
(1821, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/vnTxBw872dU', 'A psychological plot twist | #keyandpeele #halloween #horrorstories', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf.', 'https://i.ytimg.com/vi/vnTxBw872dU/hqdefault.jpg'),
(1822, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/zw7tZBEWeKU', '&quot;Lookin&#39; like a couple of clowns...&quot; | #shorts #keyandpeele', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf.', 'https://i.ytimg.com/vi/zw7tZBEWeKU/hqdefault.jpg'),
(1823, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/ZAFFBlliv70', 'Best Basketball Sketches 🏀 - Key &amp; Peele', 'All-star shooting guard Charlie Sanders literally deals with Adversity, basketball champion Charlie Sanders feels a little too ...', 'https://i.ytimg.com/vi/ZAFFBlliv70/hqdefault.jpg'),
(1824, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/OJKtQDTdvR4', 'What a mess. | #keyandpeele #shorts', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf.', 'https://i.ytimg.com/vi/OJKtQDTdvR4/hqdefault.jpg'),
(1825, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/7whqVDLieRs', 'Wildest Murder Sketches - Key &amp; Peele', 'A detective tracks a serial killer into a hall of mirrors, a rapper is interrogated over his very revealing concept album, and an ...', 'https://i.ytimg.com/vi/7whqVDLieRs/hqdefault.jpg'),
(1826, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/QN488Ao-G20', 'Most Badass Action Stars 💥- Key &amp; Peele', 'A retro action hero infiltrates a Colombian crime boss\' residence, a superhero squad has a discrimination problem, and an L.A. ...', 'https://i.ytimg.com/vi/QN488Ao-G20/hqdefault.jpg'),
(1827, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/wOBNm_8zw4I', 'How it feels to talk to someone who always says &quot;Awkward!&quot; | #shorts #keyandpeele', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf.', 'https://i.ytimg.com/vi/wOBNm_8zw4I/hqdefault.jpg'),
(1828, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/V5kzVifGYbk', 'Funniest Crying Sketches 😭 Key &amp; Peele', 'A gangster\'s crew tries not to laugh at his manly tears, a grown ass man doesn\'t like being treated like a child, and Andre\'s ...', 'https://i.ytimg.com/vi/V5kzVifGYbk/hqdefault.jpg'),
(1829, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/ppJTKgT2VFs', 'This is what an inner-city wizard school is like. #Shorts #KeyAndPeele #HarryPotter', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf.', 'https://i.ytimg.com/vi/ppJTKgT2VFs/hqdefault.jpg'),
(1830, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/_rpiv3yiYGs', 'Wildest Party Sketches - Key &amp; Peele', 'A bachelor party gets weird, a Halloween party guest takes his Michael Jackson impression too far, and a documentary profiles ...', 'https://i.ytimg.com/vi/_rpiv3yiYGs/hqdefault.jpg'),
(1831, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/zF6EmI-zSNs', 'Getting branded for a fraternity can go awry. | #shorts #keyandpeele #shorts', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf.', 'https://i.ytimg.com/vi/zF6EmI-zSNs/hqdefault.jpg'),
(1832, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/8yiKMVG3TNw', 'Top 5 Football Sketches 🏈 Key &amp; Peele', 'The all-time most watched football sketches from Key & Peele: 5. Quarterback Concussion 4. East/West Bowl: Pro Edition 3.', 'https://i.ytimg.com/vi/8yiKMVG3TNw/hqdefault.jpg'),
(1833, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/YFmNXfOkaI8', 'Wait for the drop. #shorts #KeyAndPeele #dubstep', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf.', 'https://i.ytimg.com/vi/YFmNXfOkaI8/hqdefault.jpg'),
(1834, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/HW_w6k0aOV4', 'Craziest Kid Sketches - Key &amp; Peele', 'A man has a hard time bonding with his fiancée\'s son, a dad promises his son he\'ll live forever, and a babysitter meets his match ...', 'https://i.ytimg.com/vi/HW_w6k0aOV4/hqdefault.jpg'),
(1835, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/mN_JZPmY36E', 'TFW you&#39;re too predictable | #Shorts #KeyAndPeele', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf.', 'https://i.ytimg.com/vi/mN_JZPmY36E/hqdefault.jpg'),
(1836, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/iiJmrrXwJAg', 'Funniest Teachers - Key &amp; Peele', 'Mr. Garvey substitutes for the day, a cool teacher faces off with the class clown, and the show explores what it would be like if we ...', 'https://i.ytimg.com/vi/iiJmrrXwJAg/hqdefault.jpg'),
(1837, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/iW1CLKxdLwQ', 'Secret Emotions – Key &amp; Peele', 'An R&B singer makes a surprising admission in the middle of a concert. #VMAs Paramount+ is here! Stream Key & Peele now on ...', 'https://i.ytimg.com/vi/iW1CLKxdLwQ/hqdefault.jpg'),
(1838, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/PSNAll7jjqA', 'Human or alien in disguise? The foolproof way to tell | #keyandpeele #shorts', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf #shorts.', 'https://i.ytimg.com/vi/PSNAll7jjqA/hqdefault.jpg'),
(1839, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/yRRQNzGv6Ec', 'Best of Pop Stars 🎤 Key &amp; Peele', 'A sex-positive pop star fields questions from fans about the impact that her music has had on their lives, Ray Parker, Jr. promotes ...', 'https://i.ytimg.com/vi/yRRQNzGv6Ec/hqdefault.jpg'),
(1840, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/T_jNVmRfqqw', 'Relax, Little Homie is here. | #keyandpeele  #shorts', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf #shorts.', 'https://i.ytimg.com/vi/T_jNVmRfqqw/hqdefault.jpg'),
(1841, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/fwczhLCz7-Y', 'Time Travel to the 60s with Key &amp; Peele', 'A man meets his fiancé\'s bigoted parents, a woman turns a holiday classic on its head, and an activist finds Martin Luther King ...', 'https://i.ytimg.com/vi/fwczhLCz7-Y/hqdefault.jpg'),
(1842, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/2-aJWBmp2yY', 'Pucker up, bro. | #Shorts #keyandpeele', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf.', 'https://i.ytimg.com/vi/2-aJWBmp2yY/hqdefault.jpg'),
(1843, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/17R3JjrsiZw', 'Best TV Show Parodies - Key &amp; Peele', 'Tune into “Gideon\'s Kitchen,” “Judge Jessie,” “Who Thinks They Can Dance,” “Undercover Boss,” and find out what really went on ...', 'https://i.ytimg.com/vi/17R3JjrsiZw/hqdefault.jpg'),
(1844, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/bhddgKeYWo0', 'Harriet Tubman did her own stunts.| #Shorts #keyandpeele', 'Paramount+ is here! Stream Key & Peele now on Paramount+. Try it FREE at https://bit.ly/3qyOeOf.', 'https://i.ytimg.com/vi/bhddgKeYWo0/hqdefault.jpg'),
(1845, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/CoFjr3pgjCg', 'All-Time Most Watched Sketches - Key &amp; Peele', 'The internet\'s most popular Key & Peele sketches of all time: 5. East/West College Bowl 4. Wendell\'s Pizza Order 3. I Said Bitch 2.', 'https://i.ytimg.com/vi/CoFjr3pgjCg/hqdefault.jpg'),
(1846, 'UCdN4aXTrHAtfgbVG9HjBmxQ', 'https://www.youtube.com/embed/5xFrbWVZHL4', 'Funniest Fart Sketches - Key &amp; Peele', 'A substitute teacher leaves quite the impression on his students, a tailor begins to think that the man whose measurements he\'s ...', 'https://i.ytimg.com/vi/5xFrbWVZHL4/hqdefault.jpg'),
(1847, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/4DMzmxVcC8U', 'Margaret is the killer!', 'Si Margaret ang pumatay kay Gustavo! Mapapanood ang full episodes ng “The Royal Blood“ overseas sa GMA Pinoy TV.', 'https://i.ytimg.com/vi/4DMzmxVcC8U/hqdefault.jpg'),
(1848, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/x3MaSv34A68', 'Belinda, nalaman na ang nangyari sa anak!', 'Masakit para kay Belinda ang nangyari kay Monique at hindi siya titigil para mahanap ito. Mapapanood ang full episodes ng ...', 'https://i.ytimg.com/vi/x3MaSv34A68/hqdefault.jpg'),
(1849, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/dUgBu0IxFYc', 'Dino, hindi welcome sa bahay ni Carding', 'Nakita ulit ni Monique alyas Dino si Carding pero hindi siya pinatuloy sa tahanan nito. Sad. :( Mapapanood ang full episodes ng ...', 'https://i.ytimg.com/vi/dUgBu0IxFYc/hqdefault.jpg'),
(1850, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/hl6Xu4wnzhQ', 'Millie, humiwalay muna sa asawa', 'Right decision ba ang maghiwalay muna sina Millie at Anton? Mapapanood ang full episodes ng “The Missing Husband” ...', 'https://i.ytimg.com/vi/hl6Xu4wnzhQ/hqdefault.jpg'),
(1851, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/kizWTZ7kIz8', 'Mayor Magnus, may nakalap na ebidensya', 'Malalaman na ni Magnus kung sino ang source ng video ng pananakit ni Riley! Mapapanood ang full episodes ng “Magandang ...', 'https://i.ytimg.com/vi/kizWTZ7kIz8/hqdefault.jpg'),
(1852, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/xjv14C8UqOs', 'Jared is falling for Greta V.!', 'OMG! Nagparamdam si Jared kay Greta V.!!! Mapapanood ang full episodes ng “Magandang Dilag” overseas sa GMA Pinoy TV.', 'https://i.ytimg.com/vi/xjv14C8UqOs/hqdefault.jpg'),
(1853, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/ys7WG9CfKCY', 'Lyneth, tinanggihan si Doc Carlos?', 'Bakeeeeeeet, Lyneth? Mapapanood ang full episodes ng “Abot-Kamay na Pangarap” overseas sa GMA Pinoy TV. Bisitahin lang ...', 'https://i.ytimg.com/vi/ys7WG9CfKCY/hqdefault.jpg'),
(1854, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/MJdzlvqu9UE', 'Doc Carlos, nag-propose kay Lyneth!', 'Is it a yes or no for Doc Carlos? Mapapanood ang full episodes ng “Abot-Kamay na Pangarap” overseas sa GMA Pinoy TV.', 'https://i.ytimg.com/vi/MJdzlvqu9UE/hqdefault.jpg'),
(1855, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/i1rlJb2YkzE', 'Sugar Mercado, sumalang sa fast talk!', 'Tito Boy: \"Oo o hindi, nagkaalitan ba kayo ni Herlene Budol?\" Sugar Mercado: \"Haaa?\" Panoorin ang video para sa buong sagot!', 'https://i.ytimg.com/vi/i1rlJb2YkzE/hqdefault.jpg'),
(1856, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/6akb1LTmYCw', 'Aira Bermudez, sumalang sa fast talk!', 'Sinagot ni Aira Bermudez kung sino sa Sexbomb girls ang pinakamagaling sumayaw at pinakamahirap makakuha ng steps!', 'https://i.ytimg.com/vi/6akb1LTmYCw/hqdefault.jpg'),
(1857, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/MA_1f-uBMpQ', 'Alden Richards and Michelle Dee crown Miss Filipina International 2023', 'Sparkle artists Alden Richards and Michelle Marquez Dee flew to California to judge the prestigious Miss Filipina International ...', 'https://i.ytimg.com/vi/MA_1f-uBMpQ/hqdefault.jpg'),
(1858, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/xUMt8triAN0', 'September is Seafarer&#39;s Month!', 'Despite being away from home, your smiles bring comfort to your families as they wait for your return. GMA Pinoy TV salutes all ...', 'https://i.ytimg.com/vi/xUMt8triAN0/hqdefault.jpg'),
(1859, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/-L9Pq1BdTc8', 'Doc RJ, pagod na kay Moira?', 'Sino ba naman kasi ang hindi mapapagod sa ugali ni Moira?! Kaya nagsasawa na si Doc RJ sa kanya. Mapapanood ang full ...', 'https://i.ytimg.com/vi/-L9Pq1BdTc8/hqdefault.jpg'),
(1860, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/XtVJJTqMaS0', 'Dr. Analyn, itinatago si Doc RJ?', 'Maawa kaya si Analyn kay Zoey at sabihin kung nasaan si Doc RJ? Mapapanood ang full episodes ng “Abot-Kamay na ...', 'https://i.ytimg.com/vi/XtVJJTqMaS0/hqdefault.jpg'),
(1861, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/LOBTi3aEEqE', 'Franco Finn: You got to own your uniqueness', '\"You got to own your uniqueness. Just believe in you.\" Here\'s your #MondayMotivation from Filipino-American hype man of the ...', 'https://i.ytimg.com/vi/LOBTi3aEEqE/hqdefault.jpg'),
(1862, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/IYG-22glO84', 'Fil-Am NBA hypeman Franco Finn talks about working with Stephen Curry of the Golden State Warriors', 'How does it feel to be working with the best players of the Golden State Warriors including Stephen Curry? Let\'s listen to this story ...', 'https://i.ytimg.com/vi/IYG-22glO84/hqdefault.jpg'),
(1863, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/9Ju4HZhAwJE', 'Kristoff, pinatay ang ina?', 'Namili si Kristoff sa pagitan ng posisyon sa kumpanya at buhay ng kanyang ina. Mapapanood ang full episodes ng “The Royal ...', 'https://i.ytimg.com/vi/9Ju4HZhAwJE/hqdefault.jpg'),
(1864, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/9zg_djogvSQ', 'Moira, binalaan si Doc Carlos', 'Moira to Doc Carlos: \"Kapag hindi mo binakuran si Lyneth, aagawin at aagawin siya ng asawa ko.\" Mapapanood ang full ...', 'https://i.ytimg.com/vi/9zg_djogvSQ/hqdefault.jpg'),
(1865, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/oqwn8YD7Re0', 'Dennis Trillo, sumalang sa fast talk!', 'Anong ugali ng babae ang nakaka-turn on at turn off kay Dennis Trillo? At ano ang ginagawa ni Jennylyn Mercado sa kanya na ...', 'https://i.ytimg.com/vi/oqwn8YD7Re0/hqdefault.jpg'),
(1866, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/N4ErNgwQuW8', '&quot;Pangako Hanggang Sa Dulo&quot; theme song of &quot;The Missing Husband&quot;', 'WATCH: \"Pangako Hanggang Sa Dulo\" theme song of \"The Missing Husband\" performed by Denise Barbacena. Continue ...', 'https://i.ytimg.com/vi/N4ErNgwQuW8/hqdefault.jpg'),
(1867, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/MtnyZAKuRsE', 'Batang hamog na kinupkop ng isang babae, tampok sa &quot;Magpakailanman&quot;', 'Isang batang palaboy, kukupkupin ng isang babae at ituturing na sarili niyang anak. Tunghayan ang kanilang natatanging ...', 'https://i.ytimg.com/vi/MtnyZAKuRsE/hqdefault.jpg'),
(1868, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/N40oDs8FVOM', 'Kristoff, natuklasan ang sikreto nina Diana at Napoy!', 'Alam na ni Kristoff na dating boyfriend ni Diana si Napoy. Mapapanood ang full episodes ng “The Royal Blood“ overseas sa GMA ...', 'https://i.ytimg.com/vi/N40oDs8FVOM/hqdefault.jpg'),
(1869, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/QQqReEE3io4', 'Luisa, bistado na si Greta V.?', 'Matuklasan na kaya ni nanay Luisa ang mga plano ni Greta V.? Mapapanood ang full episodes ng “Magandang Dilag” overseas ...', 'https://i.ytimg.com/vi/QQqReEE3io4/hqdefault.jpg'),
(1870, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/pnFjG-D9IhU', 'Maging Sino Ka Man music video (with English subtitles)', 'WATCH: Maging Sino Ka Man music video (with English subtitles) performed by Hannah Precillas! Continue watching \"Maging ...', 'https://i.ytimg.com/vi/pnFjG-D9IhU/hqdefault.jpg'),
(1871, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/u_5Gq5HtqmY', '&quot;Love Before Sunrise&quot; coming soon this September on GMA Pinoy TV!', 'Two critically acclaimed actors - Sid Lucero and Andrea Torres join the Drama King Dennis Trillo and Box-Office Queen Bea ...', 'https://i.ytimg.com/vi/u_5Gq5HtqmY/hqdefault.jpg'),
(1872, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/cBhIzJOEPMA', 'Birthday ni Idol: Lope K. Santos', 'This month on \"Birthday ni Idol,\" we look back at the life of Lope K. Santos, the Father of Philippine Grammar. For more videos like ...', 'https://i.ytimg.com/vi/cBhIzJOEPMA/hqdefault_live.jpg'),
(1873, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/rBnxDZLbXFY', 'Stell, sumalang sa fast talk!', 'Sinagot ni Stell kung sino sa SB19 ang naughty, habulin ng babae at taken na! Mapapanood ang full episodes ng “Fast Talk with ...', 'https://i.ytimg.com/vi/rBnxDZLbXFY/hqdefault.jpg'),
(1874, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/ObZJtiZDxCU', 'Stell, hindi inasahan na magiging coach sa &quot;The Voice Generations&quot;', 'Hindi raw inasahan ni Stell na magiging coach siya sa \"The Voice Generations\" at makakasama sa isang proyekto ang mga ...', 'https://i.ytimg.com/vi/ObZJtiZDxCU/hqdefault.jpg'),
(1875, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/S9U8yS0Rtb4', 'The unexpected death of an ally', 'Nabawasan na naman ng kakampi si Greta V.! Mapapanood ang full episodes ng “Magandang Dilag” overseas sa GMA Pinoy TV ...', 'https://i.ytimg.com/vi/S9U8yS0Rtb4/hqdefault.jpg'),
(1876, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/7FMeBhLaG8s', 'Anong klaseng mentor si Chito Miranda?', 'Chito: “I always go for the underdogs. Ako \'yung coach who will focus not on the talent but on everything that revolves around it.', 'https://i.ytimg.com/vi/7FMeBhLaG8s/hqdefault.jpg'),
(1877, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/DP-0TRkNG7U', 'Music Video of &quot;Maging Sino Ka Man&quot;', 'Handa ka na bang kiligin sa muling pagtatambal nina Barbie Forteza at David Licauco? Damhin muna natin ang theme song ng ...', 'https://i.ytimg.com/vi/DP-0TRkNG7U/hqdefault.jpg'),
(1878, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/DO9QME5GoYU', 'Mayor Magnus, dinalaw si Allison sa ospital', 'Magnus: \"Hindi ko kayang mawala ka.\" Allison: \"What are you trying to say?\" Magnus: \"Ang sinasabi ko sa iyo, kahit ...', 'https://i.ytimg.com/vi/DO9QME5GoYU/hqdefault.jpg'),
(1879, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/bOqiwSzktZE', 'Oh Wow by Bubble Gang', 'Marami bang uhaw sa followers, likes at subscribers? Gusto ninyo rin ba ang mag-trend o mag-viral? Ito ang kantang bagay sa ...', 'https://i.ytimg.com/vi/bOqiwSzktZE/hqdefault.jpg'),
(1880, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/6yPp_yyZBH8', 'Watch &quot;Parang Kayo Pero Hindi&quot; on GMA Life TV!', 'Alam mo \'yung parang kayo pero hindi? Ang labo \'no? Panoorin sina Marco Gumabao, Kylie Verzosa at Xian Lim sa \"Parang ...', 'https://i.ytimg.com/vi/6yPp_yyZBH8/hqdefault.jpg'),
(1881, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/NzQinCwEjHo', 'Enjoy &quot;The Binge Life&quot; on GMA Life TV!', 'Who doesn\'t want a hearty laugh or a thrilling mystery? Who doesn\'t want to enjoy moments that sweep you off your feet or the ...', 'https://i.ytimg.com/vi/NzQinCwEjHo/hqdefault.jpg'),
(1882, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/p6YVXd9FWzk', 'Iya Villania, na-sister zone ni Drew Arellano noon!', 'Alam ba ninyong tinawag ni Drew Arellano na \"little sister\" si Iya Villania noon at nagulat siya nang una siyang halikan ni Iya!', 'https://i.ytimg.com/vi/p6YVXd9FWzk/hqdefault.jpg'),
(1883, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/NdJYvanYBKg', 'Drew and Iya Arellano&#39;s relationship hacks!', 'Gusto niyo rin ba maging #couplegoals tulad nina Drew at Iya Arellano? Alamin ang kanilang tactic para sa isang smooth sailing ...', 'https://i.ytimg.com/vi/NdJYvanYBKg/hqdefault.jpg'),
(1884, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/6c5050Obue8', 'Drew and Iya Arellano, sumalang sa fast talk!', 'Bakit pinagselosan ni Drew Arellano sina Sam Milby at Diether Ocampo noon? At ano ang namana ng mga anak nila sa kanila ni ...', 'https://i.ytimg.com/vi/6c5050Obue8/hqdefault.jpg'),
(1885, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/dkLvAP6tc2M', 'Namazuka, nagpakitang gilas!', 'In all fairness, mukhang mahusay ang pagkakabuo ng mga Boazanian sa beast fighter na si Namazuka. Pero hanggang saan ...', 'https://i.ytimg.com/vi/dkLvAP6tc2M/hqdefault.jpg'),
(1886, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/_heQJDNjOHI', '&quot;Voltes V&quot; team, defeated?', 'Gising, team! Kailangan kayo ng planetang Earth! Mapapanood ang full episodes ng “Voltes V: Legacy“ overseas sa GMA Pinoy ...', 'https://i.ytimg.com/vi/_heQJDNjOHI/hqdefault.jpg'),
(1887, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/xodJAZTK6Ik', 'Jared, nagpakilig na naman', 'Jared, ano ba! Palagi ka na lang nagpapakilig. Hindi na namin kaya. Mapapanood ang full episodes ng “Magandang Dilag” ...', 'https://i.ytimg.com/vi/xodJAZTK6Ik/hqdefault.jpg'),
(1888, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/6ntqC4QhTok', 'Goodbye, diary?', 'Hala! Bakit mo itinapon ang diary, Kudos? Mapapanood ang full episodes ng “Luv is: Love at First Read“ overseas sa GMA Pinoy ...', 'https://i.ytimg.com/vi/6ntqC4QhTok/hqdefault.jpg'),
(1889, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/hM0_gUU5HTA', 'Napoy, tatraydurin ng kaibigan?', 'Mag-ingat ka sa mga taong nakapaligid sa iyo, Napoy! Mapapanood ang full episodes ng “The Royal Blood“ overseas sa GMA ...', 'https://i.ytimg.com/vi/hM0_gUU5HTA/hqdefault.jpg'),
(1890, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/9w6sbzd4mF8', 'Eileen, alone and grieving', 'Ano ba ang dapat gawin ni Eileen para mapatawad n\'yo siya? Mapapanood ang full episodes ng “The Seed of Love” overseas sa ...', 'https://i.ytimg.com/vi/9w6sbzd4mF8/hqdefault.jpg'),
(1891, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/IP7si-Ch7ss', 'Joaquin, nagbabalik?', 'Nagbalik si Joaquin para humingi ng tawad at makausap si Gigi pero may babalikan pa kaya siyang pamilya? Mapapanood ang ...', 'https://i.ytimg.com/vi/IP7si-Ch7ss/hqdefault.jpg'),
(1892, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/uaTyLVHolOo', 'Gigi, nakita na ang kanyang tatay?', 'Nagkita na nga ba sina Gigi at ang tatay niyang si Joaquin? Mapapanood ang full episodes ng “Magandang Dilag” overseas sa ...', 'https://i.ytimg.com/vi/uaTyLVHolOo/hqdefault.jpg'),
(1893, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/QU1aIIsci2Y', 'Gigi, natikman ang galit ni Blaire!', 'Maganda nga pero ang sama naman ng ugali nitong si Blaire! Mapapanood ang full episodes ng “Magandang Dilag” overseas sa ...', 'https://i.ytimg.com/vi/QU1aIIsci2Y/hqdefault.jpg'),
(1894, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/VeW7DQj2raU', 'Doc RJ, nakita na si Lyneth!', 'Ano ang kahahantungan ng pagkikita nina Doc RJ at Lyneth? Exciting! Mapapanood ang full episodes ng “Abot-Kamay na ...', 'https://i.ytimg.com/vi/VeW7DQj2raU/hqdefault.jpg'),
(1895, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/YGHOhCiM-9U', 'Conjoined twins, nag-aaway tungkol sa surgery', 'Hindi pa final ang desisyon ng conjoined twins tungkol sa kanilang surgery. Ano ang mas mananaig? Mapapanood ang full ...', 'https://i.ytimg.com/vi/YGHOhCiM-9U/hqdefault.jpg'),
(1896, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/a2L0aeB9l04', 'Herlene Budol, sinagot ang mga kritisismo tungkol sa kanya', 'Herlene Budol, sinagot ang mga kritisismo tungkol sa kanya sa Miss Grand Philippines Question and Answer portion.', 'https://i.ytimg.com/vi/a2L0aeB9l04/hqdefault.jpg'),
(1897, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/Bkkfi7J0v4Q', 'Fast Talk with &#39;Magandang Dilag&#39; Herlene Budol', 'Boy: Sinong Kapuso actor ang gusto mong maka-kissing scene? Herlene: Alden Richards! Mapapanood ang full episodes ng ...', 'https://i.ytimg.com/vi/Bkkfi7J0v4Q/hqdefault.jpg'),
(1898, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/Bp4gErpH2lo', 'Joshua Garcia, big fan ng animes na One Piece at Attack on Titan!', 'Alam n\'yo ba na ang \"Unbreak My Heart\" star na si Joshua Garcia, big fan pala ng anime? Ang paborito niya nga ay \"One Piece\" ...', 'https://i.ytimg.com/vi/Bp4gErpH2lo/hqdefault.jpg'),
(1899, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/FeYQSZDLhQk', 'Kapuso 101: Richard Yap', 'He entered showbiz in his 40s. Now, he is one of the Kapuso Network\'s well-rounded actors! Get to know more about Richard Yap ...', 'https://i.ytimg.com/vi/FeYQSZDLhQk/hqdefault.jpg'),
(1900, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/5gSAXrogowE', 'Gigi&#39;s family struggle', 'Iyong mapapalayas na sina Gigi sa bahay, hindi pa niya alam. Mapapanood ang full episodes ng “Magandang Dilag” overseas ...', 'https://i.ytimg.com/vi/5gSAXrogowE/hqdefault.jpg'),
(1901, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/3h8YebbeOOM', 'Gigi, kilig mode?', 'Iyong kahit may pangit na nangyari kay Gigi, nakangiti pa rin siya. Ano beh! Mapapanood ang full episodes ng “Magandang ...', 'https://i.ytimg.com/vi/3h8YebbeOOM/hqdefault.jpg'),
(1902, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/tI9cNbVXlmY', 'Pinoy seafarer, sinagip ang dalawang Amerikano na na-stuck sa dagat', 'Sa tulong ng global Pinoy seafarer na si Raul Deocadez Jr., nasagip ang buhay ng dalawang American citizens matapos ...', 'https://i.ytimg.com/vi/tI9cNbVXlmY/hqdefault.jpg'),
(1903, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/YDtgZaSn9vE', 'Eileen, napuno na kay Alexa?', 'Huwag mo kasing ginagalit si Eileen, Alexa! Mapapanood ang full episodes ng “The Seed of Love” overseas sa GMA Pinoy TV.', 'https://i.ytimg.com/vi/YDtgZaSn9vE/hqdefault.jpg'),
(1904, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/mpYjJ20lIF8', 'Watch &quot;Love You Stranger&quot; starting July 3 on GMA Life TV!', '\"Para sa akin, mas nakakatakot \'yung lilom na kumakapit sa isip at hindi mo na matanggal.\" Catch Gabbi Garcia and Khalil ...', 'https://i.ytimg.com/vi/mpYjJ20lIF8/hqdefault.jpg'),
(1905, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/GlbnvmVcDVI', 'Who is Diana Royales?', 'Ano ang kaugnayan ni Diana Royales kay Napoy? Mapapanood ang full episodes ng “The Royal Blood“ overseas sa GMA Pinoy ...', 'https://i.ytimg.com/vi/GlbnvmVcDVI/hqdefault.jpg'),
(1906, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/z0n_Z1uzRb4', 'The one that got away', 'OMG! Nagbalik ang \"The One That Got Away\" o TOTGA ni Kudos! Paano na si Angelica? Mapapanood ang full episodes ng “Luv ...', 'https://i.ytimg.com/vi/z0n_Z1uzRb4/hqdefault.jpg'),
(1907, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/cCYGtZfdjlw', 'Gigi, nakatanggap ng job offer!', 'May stepping stone na si Gigi para sa pangarap niya! Mapapanood ang full episodes ng “Magandang Dilag” overseas sa GMA ...', 'https://i.ytimg.com/vi/cCYGtZfdjlw/hqdefault.jpg'),
(1908, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/LREDBBFeL0s', 'Gigi&#39;s knight in shining armor', 'Jared saved the day! Siya talaga yata ang prince charming mo, Gigi! Mapapanood ang full episodes ng “Magandang Dilag” ...', 'https://i.ytimg.com/vi/LREDBBFeL0s/hqdefault.jpg'),
(1909, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/CDbQMEQ2L60', '8th beast fighter reveal!', 'Si Namazuka na ba ang beast fighter na tatalo sa \"Voltes V\" team? Mapapanood ang full episodes ng “Voltes V: Legacy“ ...', 'https://i.ytimg.com/vi/CDbQMEQ2L60/hqdefault.jpg'),
(1910, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/WwYYZEdbl5M', 'General Zuhl, bumida kay Prince Zardoz!', 'Naks naman! Bidang-bida si Zuhl kay Prince Zardoz ngayon ha! Mapapanood ang full episodes ng “Voltes V: Legacy“ overseas ...', 'https://i.ytimg.com/vi/WwYYZEdbl5M/hqdefault.jpg'),
(1911, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/utMRapLNhnA', 'Doc RJ, muntik nang makita si Lyneth', 'Doc RJ, nasa iisang lugar lang kayo ni Lyneth! Iisang tao lang din ang pareho n\'yong kinausap! Sayang!!! Mapapanood ang full ...', 'https://i.ytimg.com/vi/utMRapLNhnA/hqdefault.jpg'),
(1912, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/BKjx2_de4k0', 'Dr. Meneses, pinagsabihan ni Moira', 'Si Dr. Ray Meneses ay kaibigan ni Doc RJ, Moira... kaya okay lang siguro na magkuwento siya tungkol sa nakaraan nito.', 'https://i.ytimg.com/vi/BKjx2_de4k0/hqdefault.jpg'),
(1913, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/a0zKrG-uqMM', 'Yes or no with Ricci Rivero', 'Tito Boy: \"Ricci, is this relationship [with Andrea Brillantes] over? Yes or no?\" Ricci Rivero: \"For now, yes.\" Tito Boy: \"It is over.', 'https://i.ytimg.com/vi/a0zKrG-uqMM/hqdefault.jpg'),
(1914, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/PtoYAQJ3bNQ', 'Ricci Rivero on winning Andrea Brillantes back', 'Tito Boy: \"Did you try to win her back?\" Ricci Rivero: \"No... kasi for the longest time, I was trying not to give up on the relationship ...', 'https://i.ytimg.com/vi/PtoYAQJ3bNQ/hqdefault.jpg'),
(1915, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/89zVLzpe1Rs', 'Joshua Garcia, paano pinaghahandaan ang mga kissing scenes niya?', 'Madalas daw mukbangin ni Joshua Garcia ang mga nakaka-kissing scene niya! Paano nga ba niya pinaghahandaan ang ...', 'https://i.ytimg.com/vi/89zVLzpe1Rs/hqdefault.jpg'),
(1916, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/8o1rRcTmpmw', 'Ricci Rivero, apektado ang pamilya', 'Hiling ni Ricci Rivero na huwag nang idamay ang kanyang pamilya sa hiwalayan nila ni Andrea Brillantes. Mapapanood ang full ...', 'https://i.ytimg.com/vi/8o1rRcTmpmw/hqdefault.jpg'),
(1917, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/h6eeDOjOnCc', 'Kapuso 101: Gabbi Garcia', 'Gabbi Garcia is an actress, global endorser, singer, host, and a vlogger! Learn more about her in this #Kapuso101 video!', 'https://i.ytimg.com/vi/h6eeDOjOnCc/hqdefault.jpg'),
(1918, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/gbHM5qFYDdg', 'Buhay ng isang seafarer, ating alamin mula kay Christopher Tuazon!   Unang Hirit', 'Seafarer, viral ang content sa TikTok! Kilalanin natin siya sa video na ito ng Unang Hirit! Mapapanood ang \"Unang Hirit\" sa GMA ...', 'https://i.ytimg.com/vi/gbHM5qFYDdg/hqdefault.jpg');
INSERT INTO `youtube_channel_videos` (`v_id`, `yc_id`, `video_link`, `title`, `description`, `thumbnail`) VALUES
(1919, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/VZZjn63vavc', 'Gigi, dream-come-true ang makasama si Jared?!', 'Sandaleeee! Nananaginip ka lang ba, Gigi o totoong halos nakayakap na sa iyo si Jared?! Suwerte mo, girl! Mapapanood ang full ...', 'https://i.ytimg.com/vi/VZZjn63vavc/hqdefault.jpg'),
(1920, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/dPJjZJtGKMw', 'Bruno Mars, may inihandang impromptu para sa kanyang Pinoy fans', 'Sa kanyang concert nitong nakaraang weekend, isang impromptu song ang inawit ni Bruno Mars para sa kanyang mga ...', 'https://i.ytimg.com/vi/dPJjZJtGKMw/hqdefault.jpg'),
(1921, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/6E5NhY-dbS4', 'Gigi, pangarap maging beauty queen!', 'May malalim na dahilan kung bakit gusto ni Gigi ang maging beauty queen. Mapapanood ang full episodes ng “Magandang ...', 'https://i.ytimg.com/vi/6E5NhY-dbS4/hqdefault.jpg'),
(1922, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/cGyW5oO2d_c', 'Quick Chat with Jessica Soho', 'Sa #QuickChat video na ito, ibinahagi ni Jessica Soho ang lugar kung saan niya ipapasyal ang kaniyang team at ang sikreto niya ...', 'https://i.ytimg.com/vi/cGyW5oO2d_c/hqdefault.jpg'),
(1923, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/70N-fgCcTso', 'Kudos and Angelica&#39;s friendship', 'Uuuuuyyy bati na talaga sina Kudos at Angelica! Simula na ba ito ng inyong pagiging magka-ibigan, este magkaibigan?', 'https://i.ytimg.com/vi/70N-fgCcTso/hqdefault.jpg'),
(1924, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/iF8FX7GJots', 'Dingdong Dantes is the host of &quot;The Voice Generations&quot;!', '\"Royal Blood\" star and Kapuso Primetime King Dingdong Dantes is the host of The Voice Generations Philippines! Catch it soon ...', 'https://i.ytimg.com/vi/iF8FX7GJots/hqdefault.jpg'),
(1925, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/xAyAHVieOZg', 'Enjoy &quot;Points of View&quot; on GMA Life TV!', 'We\'ve got so much to talk about: from issues that need to be heard, people will stories to tell, and everybody\'s cup of tea.', 'https://i.ytimg.com/vi/xAyAHVieOZg/hqdefault.jpg'),
(1926, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/dZ3w4RfRlZQ', 'Gigi, ipinahiya sa beauty contest', 'Ang gaganda ninyo para pahiyain si Gigi ha! Buti na lang rumesbak ang nanay Luisa niya! Subaybayan ang “Magandang Dilag” ...', 'https://i.ytimg.com/vi/dZ3w4RfRlZQ/hqdefault.jpg'),
(1927, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/JMydNJrQ2Kc', 'Gustavo, ginalit ng magkakapatid na Royales!', 'Huwag ninyong gagalitin si Gustavo kung ayaw n\'yo marinig ang totoo! Mapapanood ang full episodes ng “The Royal Blood“ ...', 'https://i.ytimg.com/vi/JMydNJrQ2Kc/hqdefault.jpg'),
(1928, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/hQpYhbqdpww', 'Angelica, nasa kuwarto ni Kudos!', 'Pssst, Angelica! Ano ang hinahanap mo diyan sa ilalim ng kama ni Kudos? Mapapanood ang full episodes ng “Luv is: Love at ...', 'https://i.ytimg.com/vi/hQpYhbqdpww/hqdefault.jpg'),
(1929, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/oKx6XLZfPy8', 'Ang malungkot na balita', 'Paano tatanggapin ni Bobby ang malungkot na ibinalita sa kanila at ano kaya ang magiging reaction niya sa scheme ni Alexa?', 'https://i.ytimg.com/vi/oKx6XLZfPy8/hqdefault.jpg'),
(1930, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/V7vFflnzl98', 'Buhay si Hrothgar!', 'Buhay si Hrothgar at kabilang siya sa mga rebeldeng tinutugis ng Boazanian empire! Mapapanood ang full episodes ng “Voltes ...', 'https://i.ytimg.com/vi/V7vFflnzl98/hqdefault.jpg'),
(1931, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/JPk1LKUzQdk', 'General Zuhl&#39;s next game plan', 'Sinadya ni Zuhl na ipatalo ang kanilang beast fighter para mapag-aralan nang maigi ang \"Voltes V\" robot. Ano ang kanyang ...', 'https://i.ytimg.com/vi/JPk1LKUzQdk/hqdefault.jpg'),
(1932, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/epzAOt96Wbg', 'Dr. Zoey, naglabas ng nararamdaman', 'Zoey: \"All I want is a happy family. All I want is to have a peaceful life. Hindi ba puwedeng maging masaya na lang kayo para sa ...', 'https://i.ytimg.com/vi/epzAOt96Wbg/hqdefault.jpg'),
(1933, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/vL3GkyA6O40', 'Doc Carlos and Doc RJ&#39;s real talk', 'Pinayuhan ni Doc Carlos si Doc RJ na huwag lang sa side ng pamilya niya basta maniniwala. Sumunod kaya siya? Mapapanood ...', 'https://i.ytimg.com/vi/vL3GkyA6O40/hqdefault.jpg'),
(1934, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/6vKyhpHJaVE', 'Dolly De Leon, kabilang sa cast ng Nine Perfect Strangers Season 2', 'Dolly De Leon, kabilang sa cast ng Nine Perfect Strangers Season 2! Panoorin ang buong detalye sa video na ito ng Unang Hirit!', 'https://i.ytimg.com/vi/6vKyhpHJaVE/hqdefault.jpg'),
(1935, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/Mso4IslINbw', 'Responsibilidad ng pagtulong sa mga inabusong OFW, ililipat sa DMW simula July 1', 'Simula July 1, ang Department of Migrant Workers na ang may responsibilidad sa pagtulong sa mga inaabusong OFW. Panoorin ...', 'https://i.ytimg.com/vi/Mso4IslINbw/hqdefault.jpg'),
(1936, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/j_9D9BhAgSk', 'Ricci Rivero, nilinaw ang relasyon kay Councilor Leren Bautista', 'Tito Boy: \"Mayroon ka bang relasyon kay Councilor Leren Bautista?\" Ricci Rivero: \"Wala po.\" Mapapanood ang full episodes ng ...', 'https://i.ytimg.com/vi/j_9D9BhAgSk/hqdefault.jpg'),
(1937, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/9fxihNZ7xrY', 'Ricci Rivero, binasag na ang katahimikan!', 'Inilahad ni Ricci Rivero na pinagtalunan nila ni Andrea Brillantes ang nakitang babae sa bahay niya. Mapapanood ang full ...', 'https://i.ytimg.com/vi/9fxihNZ7xrY/hqdefault.jpg'),
(1938, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/jq-s1-jMGUU', 'UK-based Pinay nurse, ginawaran ng Medalist of the Order of the British Empire', 'Isang UK-based Pinay nurse ang ginawaran ng Medalist of the Order of the British Empire. Kilalanin natin siya sa video na ito ng ...', 'https://i.ytimg.com/vi/jq-s1-jMGUU/hqdefault.jpg'),
(1939, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/RSB_7wOEpIU', 'Watch &quot;Royal Blood&quot; on GMA Pinoy TV!', 'Sino ang totoong killer ni Gustavo Royales? Isa ba ito sa kanyang mga anak? Subaybayan ang \"Royal Blood\" sa GMA Pinoy TV!', 'https://i.ytimg.com/vi/RSB_7wOEpIU/hqdefault.jpg'),
(1940, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/qcqvl_9QDGs', 'PH Embassy sa Moscow patuloy na pinag-iingat ang mga Pinoy sa Russia', 'PH Embassy sa Moscow patuloy na pinag-iingat ang mga Pinoy sa Russia sa gitna ng tensyon doon. Panoorin ang buong ulat sa ...', 'https://i.ytimg.com/vi/qcqvl_9QDGs/hqdefault.jpg'),
(1941, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/yF0tFGqze3g', 'SB19, matagumpay ang isinagawang back-to-back concert!', 'Matagumpay ang isinagawang back-to-back concert ng Ppop group na SB19 nitong weekend. Kasunod nito, magpe-perform din ...', 'https://i.ytimg.com/vi/yF0tFGqze3g/hqdefault.jpg'),
(1942, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/fVSu_4uFUUA', 'Watch &quot;Love You Stranger&quot; starting July 3 on GMA Life TV!', 'They cannot run from the past. The curse will keep following them. Catch Gabbi Garcia and Khalil Ramos on \"Love You Stranger\" ...', 'https://i.ytimg.com/vi/fVSu_4uFUUA/hqdefault.jpg'),
(1943, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/2Xjp3vXkuNg', 'Mga Pilipinong public nurse sa New York City, nagprotesta', 'Nagprotesta ang ilang Pilipinong public nurse sa New York City kamakailan. Bakit kaya? Alamin sa video na ito ng Unang Hirit.', 'https://i.ytimg.com/vi/2Xjp3vXkuNg/hqdefault.jpg'),
(1944, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/Xp0v5HIb_kI', 'Seafarer Fiesta, dinagsa ng mga marino at kani-kanilang pamilya', 'Dinagsa ng mga marino at kani-kanilang pamilya ang isinagawang Seafarer Fiesta nitong weekend. Ito ay inorganisa ng ...', 'https://i.ytimg.com/vi/Xp0v5HIb_kI/hqdefault.jpg'),
(1945, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/bhRKdSpA7Es', 'Tatlong Pinoy na nakakulong sa UAE, palalayain', 'Nakatakdang palayain ang tatlong Pilipinong nakakulong ngayon sa United Arab Emirates kasunod ng pagbibigay ng ...', 'https://i.ytimg.com/vi/bhRKdSpA7Es/hqdefault.jpg'),
(1946, 'UCJUPKQNFPmKZjn95sIQDFmQ', 'https://www.youtube.com/embed/e4yEr4jxLMA', 'Quick Chat with the cast of &quot;Magandang Dilag&quot;', 'Paano nga ba nagiging maganda ang isang dilag? At sino ang magandang dilag para kina Herlene Budol, Chanda Romero, ...', 'https://i.ytimg.com/vi/e4yEr4jxLMA/hqdefault.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `youtube_channels`
--
ALTER TABLE `youtube_channels`
  ADD PRIMARY KEY (`y_id`);

--
-- Indexes for table `youtube_channel_videos`
--
ALTER TABLE `youtube_channel_videos`
  ADD PRIMARY KEY (`v_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `youtube_channels`
--
ALTER TABLE `youtube_channels`
  MODIFY `y_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=124;

--
-- AUTO_INCREMENT for table `youtube_channel_videos`
--
ALTER TABLE `youtube_channel_videos`
  MODIFY `v_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1947;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
